#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
import rosbag
import ipfsapi
import math
from robonomics_msgs.msg import Demand, Result, Multihash
from tempfile import NamedTemporaryFile
from std_msgs.msg import UInt32, String

class PublishData:
    MODEL = "QmQsMXoZKPNtGoTMpiGASU2Xxk6cJnEWdj7Bdt9mJo6UFD"
    TOKEN = "0x98DFc5247da729c045D4938bABD081A61a455776"

    def __init__(self):
        rospy.init_node("sensor_publisher")

        self.ipfs = ipfsapi.connect()

        self.noise = 0
        self.particle = 0

        self.pubresult = rospy.Publisher("/liability/infochan/eth/signing/result", Result, queue_size=10)

        def update_noise(data):
            voltage = data.data * (5.0 / 1023)
            self.noise = -20 * math.log10(voltage / 5.0)
        rospy.Subscriber("/noise", UInt32, update_noise)

        def update_particle(data):
            voltage = data.data * (5.0 / 1023)
            rs_gas = voltage # (5.0 - voltage) / voltage
            self.particle = 3.027 * math.pow(1.0698, rs_gas);
        rospy.Subscriber("/particle", UInt32, update_particle)

        def publish_data(demand):
            if demand.model.multihash == self.MODEL and demand.token == self.TOKEN and demand.cost == 0:
                rospy.loginfo("My model and token, cost 0")

                with NamedTemporaryFile(dir="/storage/rosbag/", delete=False) as tmpfile:
                    recorder = rosbag.Bag(tmpfile.name, 'w')

                    output = "Noise: {0:.2f} dB, CO: {0:.2f} PPM".format(self.noise, self.particle)
                    recorder.write('/worker/data', String(data=output))
                    recorder.close()

                    ipfs_response = self.ipfs.add(tmpfile.name)

                    res = Result()
                    res.liability = "0x0000000000000000000000000000000000000000"
                    res.result = Multihash(multihash=ipfs_response['Hash'])
                    res.success = True

                    self.pubresult.publish(res)

        rospy.Subscriber("/liability/infochan/incoming/demand", Demand, publish_data)

    def spin(self):
        rospy.spin()

if __name__ == "__main__":
    PublishData().spin()
